### ISSUE TITLE
Open terminal in current directory

### ISSUE THREAD

**Issue by LeviticusNelson** [NvChad/nvterm#10]
I was wondering if it would be possible to have a setting to open the terminal at the current directory/folder located.

**Comment by siduck** [comment]
i think it already opens it in cwd

**Comment by LeviticusNelson** [comment]
Mine just opens in `~/` so is there a way that I can change that?

**Comment by siduck** [comment]
cd into some dir and then open nvim 

then press alt i

**Comment by LeviticusNelson** [comment]
Sweet! That worked!

**Comment by siduck** [comment]
@LeviticusNelson manual cd can be too much work sometimes so try nvim foldername now and see if terminal updates cwd 

but make sure to update nvchad first, leader uu

**Comment by LeviticusNelson** [comment]
That's pretty good! Maybe the next step is to add a feature that goes to the first parent folder that has the .git file.

**Comment by siduck** [comment]
@LeviticusNelson  press ] in on folder name in nvimtree, it'll automatically go in it + cd into it

**Comment by LeviticusNelson** [comment]
<C-]> did the job on the folder, it also seems that nvimtree now only limits the current folder and limits telescope for finding files as well.

**Comment by siduck** [comment]
https://github.com/nvim-telescope/telescope.nvim/issues/502

**Comment by Yakov-Varnaev** [comment]
Is there a way to always open terminal in root dir?

My project steucture looks like this:

```
root
  subdir1
    file1.py
    file2.py
  subdir2
    file3.py
  manage.py
```

If I have `file1.py` opened then my terminal is opened in `root/subdir1`, even though nvim was launched in root dir.

**Comment by siduck** [comment]
> Is there a way to always open terminal in root dir?
> 
> My project steucture looks like this:
> 
> ```
> root
>   subdir1
>     file1.py
>     file2.py
>   subdir2
>     file3.py
>   manage.py
> ```
> 
> If I have `file1.py` opened then my terminal is opened in `root/subdir1`, even though nvim was launched in root dir.

cd root
nvim
then open file1 via telescope or nvimtree
open terminal to see its cwd

**Comment by Yakov-Varnaev** [comment]
Yeah, that's what do not like. I need terminal to always open at root. Is it possible?

nvim root
open file1
<M-i>
And I want terminal to be at root, not cwd of file1.

**Comment by siduck** [comment]
> Yeah, that's what do not like. I need terminal to always open at root. Is it possible?
> 
> nvim root open file1 And I want terminal to be at root, not cwd of file1.

```shell
nv() {
  [ -n "$1" ] && [ -d "$1" ] && cd "$1" && shift
  nvim "$@"
}e
```

put this into your bashrc or shell config, then nv root :)

**Comment by Yakov-Varnaev** [comment]
Well, this worked but feels a bit wierd. Shouldn't it be a part of nvterm config?

**Comment by siduck** [comment]
> Well, this worked but feels a bit wierd. Shouldn't it be a part of nvterm config?

no, thats just a shell script function!
