### ISSUE TITLE
Feature Request: Toggle All Terminals

### ISSUE THREAD

**Issue by shaun-mathew** [NvChad/nvterm#17]
Currently you can only toggle the last open terminal, but I would like to toggle all terminals in the case you have multiple terminal windows open.

**Comment by siduck** [comment]
> Currently you can only toggle the last open terminal, but I would like to toggle all terminals in the case you have multiple terminal windows open.

there will only be 3 toggleable terminals available, (float,horizontal, vertical) are u talking about that

**Comment by shaun-mathew** [comment]
Say I have 1 horizontal terminal and two vertical terminals sat the bottom open at once or multiple, I want to be able to toggle their state all at once.

![2022-08-14_01-04](https://user-images.githubusercontent.com/16690478/184523297-4ebab48f-1598-4670-af7d-0edc73ae1256.png)

**Comment by siduck** [comment]
oh those terminals are from the spawn terminal function right?

**Comment by shaun-mathew** [comment]
Yes

**Comment by siduck** [comment]
i'll add a mapping for this in nvchad repo soon

**Comment by marko911** [comment]
The mapping doesnt work for me. I press Option+H and nothing happens. Anyone have a clue ?

**Comment by siduck** [comment]
@marko911 I don't remember if I added mapping for this, did you run that toggle function?

**Comment by marko911** [comment]
in `mappings.lua` : 

```
M.nvterm = {
  plugin = true,

  t = {
    -- toggle in terminal mode
    ["<A-i>"] = {
      function()
        require("nvterm.terminal").toggle "float"
      end,
      "toggle floating term",
    },

    ["<A-h>"] = {
      function()
        require("nvterm.terminal").toggle "horizontal"
      end,
      "toggle horizontal term",
    },

    ["<A-v>"] = {
      function()
        require("nvterm.terminal").toggle "vertical"
      end,
      "toggle vertical term",
    },
  },
```

**Comment by siduck** [comment]
these are the default ones, check the function which was added in @shaun-mathew 's PR
