### ISSUE TITLE
Lazygit integration

### ISSUE THREAD

**Issue by Parry-97** [NvChad/nvterm#29]
Hi, I tried using the ```send ``` function for this and the command is successfully executed inside the spawned terminal but I can't insert on that specific terminal and the focus remains on the previously active buffer. have to toggle back to the terminal in order to work on it.
Is there another alternative to ```send``` to execute the command and to work on the terminal in insert mode ?

Very simple mapping on my side:
![image](https://user-images.githubusercontent.com/39216605/208328232-7223cf35-67fd-4013-becc-4f0f89db5295.png)

**Comment by AllanChain** [comment]
nvterm deliberately restores focus after sending the command to the terminal:

https://github.com/NvChad/nvterm/blob/29a70ef608a8cc5db3a5fc300d39a39d1a44a863/lua/nvterm/terminal.lua#L65-L80

A workaround is to use the following:

```lua
    ["<leader>gg"] = {
      function()
        local term = require("nvterm.terminal").new("float")
        vim.api.nvim_chan_send(term.job_id, "lazygit\n")
      end,
      "open Lazygit",
    },
```

**Comment by Parry-97** [comment]
Thanks, @AllanChain .
