### ISSUE TITLE
Attempt to index global terminal (nil value)

### ISSUE THREAD

**Issue by siduck** [NvChad/nvterm#3]
![image](https://user-images.githubusercontent.com/59060246/164634640-676ae1c6-732c-41b6-a1d8-e75eb5730557.png)

doesnt work :c

**Comment by siduck** [comment]
My config 
![image](https://user-images.githubusercontent.com/59060246/164635409-79931e37-ca9e-4482-8d8a-c4b395210ea7.png)

**Comment by siduck** [comment]
does nvterm still need extensions repo stuff?

**Comment by ahhshm** [comment]
> does nvterm still need extensions repo stuff?

NO. I'm using it without the extensions plugin

**Comment by siduck** [comment]
@zbirenbaum 
![image](https://user-images.githubusercontent.com/59060246/165037411-98e5a963-174d-404b-8b29-9549d348aca5.png)

**Comment by siduck** [comment]
the user has to define terminal var outside the setup of nvterm, Not a good idea imo.  you could instead run the terminal function outside the setup ig

soo: 
```lua
   mappings = {
    toggle = {
        { '<A-i>',    "float" },
        { '<A-h>',    "horizontal" },
        { '<A-v>',    "vertical"},
    }
  }
```

**Comment by zbirenbaum** [comment]
> the user has to define terminal var outside the setup of nvterm, Not a good idea imo. you could instead run the terminal function outside the setup ig
> 
> soo:
> 
> ```lua
>    mappings = {
>       toggle = {
>          { "<A-i>", "float" },
>          { "<A-h>", "horizontal" },
>          { "<A-v>", "vertical" },
>       },
>       new = {  
>          { "<C-i", "float" },
>          { "<C-h>", "horizontal" },
>          { "<C-x>", "vertical" },
>       }
>    },
> ```
> 
> Once this is implemented, I'll add it in the re-custom branch

Ok I did this, but the new float isn't going in there. People aren't going to open floats directly on top of eachother lmao.

Also, no one I've met utilizes multiple terminals the way you do, so while I respect the individuality, I'm going to make creating the 'new' mappings an opt-in flag, with defaults, so that the plugin doesn't overwrite hotkeys people are using for other stuff.

All you'll have to do is pass `{ enable_new_mappings = true }` to the setup config table.

**Comment by siduck** [comment]
oh yea , totally forgot about the floats lol!

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/165049004-695d45d7-a8e2-443c-b677-86c569852ad4.png)
 LIke this?

**Comment by siduck** [comment]
doesnt work :c

**Comment by zbirenbaum** [comment]
Its still on my dev branch. I was adding some shortcuts to the config.

**Comment by zbirenbaum** [comment]
@siduck ok its merged to main. I gotta go to sleep, but theres a new function for easily setting up new mappings, and shortcuts for configuration detailed in the readme.

I didn't update readme with the new function cuz its late, but I can tomorrow.

**Comment by siduck** [comment]
Alright!

**Comment by zbirenbaum** [comment]
wait I lied enable new mappings is broke, one sec.

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/165053793-dff1dbc6-4831-420e-9271-73a45feebe15.png)

This is confusing imo

**Comment by siduck** [comment]
It would be better to just adhere to the structure of default setup table ._.

**Comment by zbirenbaum** [comment]
ok commit amended, its working now.  

The docs do need work, I'll do that in the morning.

I forgot to implement same-size terminal splits with `new` so I'll have to do that. Right now its not gonna split too well with the `new` stuff. I need to think about how to best implement it in the current structure.

**Comment by zbirenbaum** [comment]
> It would be better to just adhere to the structure of default setup table, like all plugins do

default table has lots of nested stuff making it a pain to set just one hotkey or something. We can just include the table with shortcuts in the readme, users don't need to know the internal defaults. I've seen stuff in other plugins and I think even the neovim source that does the same.

**Comment by siduck** [comment]
@zbirenbaum C-v or C-h are default nvchad bindings, change it to leader v/h . Also i did that in the setup table and it toggles the terminal instead of spawning new terminals so Ig you forgot to use the new terminal function and just used the toggle function for all the mappings

**Comment by siduck** [comment]
unable to pick new terminals! It just shows 
![image](https://user-images.githubusercontent.com/59060246/165436037-9708aa74-4901-4752-8faa-6933061d7fd7.png)

**Comment by siduck** [comment]
leader +x => hide file buffers and terminal buffers 

Ctrl + q => close file buffers and terminal buffers (bd!)

leader + W => pick term buffers ( already implemented )
leader +  B => pick file buffers

ig it'd be a good to have feature to be able to hide/restore file buffers in v2.0 gigachad as it gets quite annoying when we have way too many files in a project and many opened (splits or in bufferline) so it gets very crowded

**Comment by zbirenbaum** [comment]
> ig it'd be a good to have feature to be able to hide/restore file buffers in v2.0 gigachad as it gets quite annoying when we have way too many files in a project and many opened (splits or in bufferline) so it gets very crowded

This is already the whole idea behind buffers. Just type :buffers and it will show all of them. :bp or :bn cycles then like bufferline does. If you try :b \<tab\> it will give you a list of the buffers you can open.

That said, I swear to god bufferline and its derivatives are the worst plugin ever made. 90% of the issues you and every other bufferline user have are solved perfectly with vim tabs. Crowding and needing to restore isn't a thing when your editor tabs are whole views of splits rather than a single file. 

I'll cut you a deal. If you  try out vim tabs and still think that the buffer restore is necessary, I'll implement it for 2.0

Here's a 1 page guide https://webdevetc.com/blog/tabs-in-vim/

**Comment by siduck** [comment]
@zbirenbaum ik tabs are useful, its cool to have different layouts ( of different file buffers ) on each tab. i use it this way it gets very crowded when there are like 10+ buffers in bufferline ;(

https://user-images.githubusercontent.com/59060246/165468412-08f2acc9-1af7-458a-bd46-40d61b783a85.mp4

**Comment by zbirenbaum** [comment]
> @zbirenbaum ik tabs are useful, its cool to have different layouts ( of different file buffers ) on each tab. i use it this way it gets very crowded when there are like 10+ buffers in bufferline ;(
> 
> 
> 
> https://user-images.githubusercontent.com/59060246/165468412-08f2acc9-1af7-458a-bd46-40d61b783a85.mp4
> 
> 
> 
>  Also it'd be nice to implement the file buffer restore thing in v2.0 itself , as the new custom implementation is ready and i need to add some themes as well. Also make base16 highlights compatible to v0.7 or you can do this part as you've already got it ready


That video is exactly why bufferline is bad. In normal vim you would have just two tabs, one for each tab. Bufferline is what's causing the crowding. Remove it and try that again and you will see what I mean. There are other plugins to make tabs look attractive that keep the tabs as tabs and not buffers.

I think I opened a PR to our base16 repo with everything done. I can supply the NvChad code highlights replacement or you can see it in the colors dir of my NvCustom repo.

**Comment by siduck** [comment]
#Todo v2.0 GigaChad release

Siduck

- Custom config simple & clear implementation (done)
- New themes in base.16 lua plun 
- Update docs and improve the homepage  
- Add packer snapshot feature for better stability (can rollback to previous versions too)  when something breaks 
- Improve syntax highlighting by adding custom treesitter highlights for each theme 

Zbirenbaum

- NvTerm spawned terminals (new function) close when leader + x is done, so hide them properly!
- Auto-resize terminals spawned (new function) by nvterm  
- File buffer hide/restore  (leader + B to pick and )
- v0.7 highlight api in base16.lua plun 

Akianonymous

- list pulled commits when updating NvChad

**Comment by siduck** [comment]
@zbirenbaum add a mapping for opening a terminal window buffer too 

![image](https://user-images.githubusercontent.com/59060246/166104464-42e7da6a-59d7-4c38-a454-bee62f3fa1b6.png)

something similar to this 

:execute 'terminal' | let b:term_type = 'wind' | startinsert <CR>"
