### ISSUE TITLE
I installed it exactly as the readme says but it is not working

### ISSUE THREAD

**Issue by Vinni-Cedraz** [NvChad/nvterm#31]
Here are my keymaps:

vim.cmd("nmap <silent> <leader>tt <cmd>lua require('nvterm').toggle()<CR>")
vim.cmd("nmap <silent> <leader>tf <cmd>lua require('nvterm').toggle('float')<CR>")
vim.cmd("nmap <silent> <leader>th <cmd>lua require('nvterm').toggle('horizontal')<CR>")
vim.cmd("nmap <silent> <leader>tv <cmd>lua require('nvterm').toggle('vertical')<CR>")
vim.cmd("nmap <silent> <leader>tb <cmd>lua require('nvterm').toggle('buffer')<CR>")
vim.cmd("nmap <silent> <leader>tt <cmd>lua require('nvterm').toggle('terminal')<CR>")
vim.cmd("nmap <silent> <leader>tw <cmd>lua require('nvterm').toggle('window')<CR>")
vim.cmd("nmap <silent> <leader>tt <cmd>lua require('nvterm').toggle('tab')<CR>")
vim.cmd("nmap <silent> <leader>twb <cmd>lua require('nvterm').toggle('winblend')<CR>")
vim.cmd("nmap <silent> <leader>twc <cmd>lua require('nvterm').toggle('winblend_cursorline')<CR>")

and this is the error that happens when I call the first:

E5108: Error executing lua [string ":lua"]:1: attempt to call field 'toggle' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk
E5108: Error executing lua [string ":lua"]:1: attempt to call field 'toggle' (a nil value)
stack traceback:
        [string ":lua"]:1: in main chunk

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/222613822-27def9d4-8b67-45fe-a2b9-ce6ff00d763e.png)

**Comment by Vinni-Cedraz** [comment]
Do you really think you have helped?

**Comment by Vinni-Cedraz** [comment]
You were the one being rude by simply copying and pasting part of the readme that I clearly stated to have already read. If someone read something (and probably many times already as it was the case) and still didn't see what was wrong, then copying and pasting is rude and helped nothing. Sometimes we are just tired and need some explaining. 
Anyway, I didn't mean no harm, stay strong and have a nice day.

**Comment by siduck** [comment]
does this command work?

lua require("nvterm.terminal").new "horizontal"

**Comment by Vinni-Cedraz** [comment]
when I tried it by typing `:require("nvterm.terminal").new "horizontal"` it did not work, should I try again with : lua require("nvterm.terminal").new "horizontal"   ?

**Comment by siduck** [comment]
> when I tried it by typing `:require("nvterm.terminal").new "horizontal"` it did not work, should I try again with `: lua require("nvterm.terminal").new "horizontal"` ?

yes lua is needed
