### ISSUE TITLE
always in insert mode

### ISSUE THREAD

**Issue by adilJamshad** [NvChad/nvterm#35]
I have experienced that terminal is always in insert mode. No matter how much "escape" key or "Ctrl+W" I press, the cursor stays in terminal,

Need work around this.

**Comment by siduck** [comment]
@adilJamshad  press Ctrl + x  if you are using nvchad. ESc and ctrl+w wont work even on vanilla nvim

**Comment by siduck** [comment]
like in general it is Ctrl+\ + Ctrl + n
