### ISSUE TITLE
How should I do to make it work at nvchad 2.0?

### ISSUE THREAD

**Issue by sheffeyG** [NvChad/nvterm#36]
I use NvChad 2.0 now, so I wanna replace code_runner.nvim with this nvterm.

so I added this to `plugins.lua`

![image](https://user-images.githubusercontent.com/57262511/230890085-7eb7b629-a69e-4f91-8b41-558dc0405308.png)

and I also made a `nvterm.lua` file in `custom/configs/`, like this

![image](https://user-images.githubusercontent.com/57262511/230890882-aa460adc-284e-488e-a69f-721f786f6e0e.png)

but sadly it does not work, how should I do to make it work?

**Comment by siduck** [comment]
@sheffey121024 thats because all plugins are lazyloaded in nvchad, either add `lazy=false` for nvterm or define those keybinds outside the nvterm config so it'll load nvterm module whenever pressing those keybinds

**Comment by sheffeyG** [comment]
I moved these codes to mappings.lua and it worked!
Thanks a lot

**Comment by siduck** [comment]
@sheffeyG  dont move all! we already have the last 3 mappings defined. just make a custom mapping for C-b , read our mappings doc.

**Comment by sheffeyG** [comment]
dont worry, I just add it like this
```lua
local ft_cmds = {
  python = "python3 " .. vim.fn.expand('%'),
}

local runcode = function()
  require("nvterm.terminal").send(ft_cmds[vim.bo.filetype], "float")
end

local M = {}

M.general = {
  n = {
    ['<A-b>'] = { runcode, opts = { noremap = true, silent = true }},
  }
}
```
it works fine. 

Anyway, I also wish the codes could be saved before I run it, so I tried this:

`['<A-b>'] = { "<cmd>w<CR> <bar> " runcode, opts = { noremap = true, silent = true }}`

but it does't work as I expect, so can I use multiple commands at once?

**Comment by siduck** [comment]
I have to sleep now, but will definitely help with this tomorrow!

**Comment by siduck** [comment]
@sheffeyG 

```lua

M.nvterm = {
  n = {
    ["<A-b>"] = {
      function()
        vim.cmd "w" -- save file

        local ft_cmds = {
          python = "python3 " .. vim.fn.expand "%",
        }

        require("nvterm.terminal").send(ft_cmds[vim.bo.filetype], "float")
      end,
      opts = { noremap = true, silent = true },
    },
  },
}
```

**Comment by sheffeyG** [comment]
> @sheffeyG
> 
> ```lua
> M.nvterm = {
>   n = {
>     ["<A-b>"] = {
>       function()
>         vim.cmd "w" -- save file
> 
>         local ft_cmds = {
>           python = "python3 " .. vim.fn.expand "%",
>         }
> 
>         require("nvterm.terminal").send(ft_cmds[vim.bo.filetype], "float")
>       end,
>      },
>   },
> }
> ```

oh that's it! thanks again
