### ISSUE TITLE
<A-h> toggle mapping doesn't work on MacOS

### ISSUE THREAD

**Issue by aceamarco** [NvChad/nvterm#38]
The `option` key on my Mac outputs special characters when I try using `<A-h>`. I've been looking online and have tried everything from adding `set macmeta` in my `init.vim` file to trying to make my own custom mapping in `mappings.lua`. Has anyone ran into this issue before?

Here's what my `mappings.lua` looks like:
```lua
---@type MappingsTable
local M = {}

M.general = {
  n = {
    [";"] = { ":", "enter command mode", opts = { nowait = true } },
  },
}

M.nvterm = {
  t = {
    ["<A-h>"] = { "<C-h>"}
  }
}

-- more keybinds!

return M

```

**Comment by siduck** [comment]
hi @aceamarco  A is alt key, probably your system is using it, are you   using iterm?

**Comment by jarroput** [comment]
I'm experiencing the same using Alacritty Version 0.11.0-rc2 (1)

**Comment by Drewbrad4** [comment]
If anyone is on iTerm2, I had to switch the Option key to `Esc+` to get the Alt commands working correctly. With Alacritty, looks like you might be able to [add a setting](https://github.com/alacritty/alacritty/issues/93#issuecomment-1428462339) to your `alacritty.yml` file to achieve the same, but I haven't tested it.

![Screenshot 2023-04-21 at 11 00 31 AM](https://user-images.githubusercontent.com/38896690/233705633-b2236034-1f4c-4b5f-baf2-d3f96bc20d9a.png)

**Comment by siduck** [comment]
yes this isnt related to nvchad. If you cant use alt on your system then just disable those keys in in your custom mappings and assign new keys to those nvterm mappings
