### ISSUE TITLE
How do I move focus out of nvterm and back to another buffer?

### ISSUE THREAD

**Issue by andradei** [NvChad/nvterm#47]
Once the terminal buffer is the active one, `<C-[hjkl]` don't work anymore to focus on another buffer and I have to use the mouse to click on another buffer.

Am I missing a keymap for that?

**Comment by andradei** [comment]
Got the keymaps with commands that do it from nvimchad in `lua/core/mappings.lua`

**Comment by dreznicek** [comment]
> 

Could you share your custom config? I'm having a hard time figuring it out.

**Comment by siduck** [comment]
> @andradei
> 
> Could you share your custom config? I'm having a hard time figuring it out.

first get out of terminal mode by C-x mapping, and then ctrl + hjkl should work
