### ISSUE TITLE
A-s doesnt work 

### ISSUE THREAD

**Issue by siduck** [NvChad/nvterm#5]
this mapping doesnt work! @zbirenbaum

**Comment by zbirenbaum** [comment]
What is it supposed to do

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/165032779-24b6991b-a43e-4201-9c45-37dc77a06e22.png)

Also u didnt define terminal before (in the readme)

**Comment by zbirenbaum** [comment]
It works for me. I'll fix the readme. Do you have A-s still set to save all files?

**Comment by siduck** [comment]
no thats for C-s

**Comment by zbirenbaum** [comment]
ok let me push my fix for the buffer close thing and then I'll look at this. 

114 lines > 1 line of code jfc

**Comment by siduck** [comment]
oo cool! :0

**Comment by siduck** [comment]
> ok let me push my fix for the buffer close thing and then I'll look at this.
> 
> 114 lines > 1 line of code jfc

BTW one thing, will it kill the terminal buffer too?

**Comment by zbirenbaum** [comment]
Put this in you chadrc and see if it works. 
```
M.mappings = {
  plugins = {},
  terminal = {
    esc_termmode = {nil},
    spawn_horizontal = {nil},
    spawn_vertical= {nil},
    new_horizontal = {nil},
    new_vertical = {nil},
  }
}
```
Literally all I do for setup is 
```
  ["NvChad/nvterm"] = {
    "NvChad/nvterm",
    config = function () require('nvterm').setup() end,
  },
```

**Comment by zbirenbaum** [comment]
> > ok let me push my fix for the buffer close thing and then I'll look at this.
> > 114 lines > 1 line of code jfc
> 
> BTW one thing, will it kill the terminal buffer too?

Yes I tested that specifically. It will close any unedited or unlisted (like terminal) automatically, and prompt the user if the file has been edited (which is safe so people don't lose hours of work)

Once we swap fully to nvterm instead of the utils function, I can have it call nvterm's hide so that it closes but is restorable.

**Comment by siduck** [comment]
> config = function () require('nvterm').setup() end,
 
 didnt work :(

**Comment by zbirenbaum** [comment]
> > config = function () require('nvterm').setup() end,
> 
> didnt work :(

Did you put the lines above that in your chadrc?

**Comment by siduck** [comment]
Also it'd be better to use 

A-h for horizontal 
A-f for floating

**Comment by siduck** [comment]
> > > config = function () require('nvterm').setup() end,
> > 
> > 
> > didnt work :(
> 
> Did you put the lines above that in your chadrc?

no i directly put it in the default plugins list, vanilla nvchad!

**Comment by siduck** [comment]
lemme share a recording

**Comment by zbirenbaum** [comment]
I'm saying that the reason I have those lines is because default nvchad has mappings that might interfere.

**Comment by siduck** [comment]
I checked the whole mappings file, we never used Alt before. Started using it for terminal when you added that terminal toggling PR

**Comment by zbirenbaum** [comment]
> Also it'd be better to use
> 
> A-h for horizontal A-f for floating

I find A-f super uncomfortable and many people are probably used to A-i from toggleterm/fterm.

I had a reason for not doing A-h but I can't remember why.

**Comment by siduck** [comment]
https://user-images.githubusercontent.com/59060246/165034951-aca11173-c986-4bfc-b369-3c8393e19d29.mp4

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/165035407-fdfe6a11-f668-4ad8-83a6-a9196abcf2ed.png)

**Comment by zbirenbaum** [comment]
@siduck I think it may be a Window manager or term hotkey interfering. I'll set A-h to be the default, but I think keeping A-i for float is a good idea.

**Comment by zbirenbaum** [comment]
Ok pull and try A-h

**Comment by siduck** [comment]
> @siduck I think it may be a Window manager or term hotkey interfering. I'll set A-h to be the default, but I think keeping A-i for float is a good idea.

oh yea that was it. A-h works!
