### ISSUE TITLE
Telescope terms doesn't seems able to open the good nvterm

### ISSUE THREAD

**Issue by t1gu1** [NvChad/nvterm#64]
If i spawn few terminal with :lua require("nvchad.term").toggle({ pos = "float" })
Write aaaaa in the first terminal and bbbbbb in the second. (Usefull to see the problem for the test)

When i play with :Telescope terms it doesn't seems to open the good terminal.

Am I doing something wrong here?

Not sure if it's about nvchad, nvterm or telescope.

**Comment by siduck** [comment]
if you use nvchad, migrate to v2.5. It doesnt use nvterm, has its own term module which is better https://nvchad.com/news/v2.5_release 
https://nvchad.com/docs/config/nvchad_ui#term

**Comment by t1gu1** [comment]
Oups wrong repo in that case. (I'll close the issue)

I use the 2.5 with nvchad.term.

I found the problem. We should give unique id for each terminal.

Something like that does the job:
:lua require("nvchad.term").toggle({ pos = "float" }, id = math.random(1, 100000))

But i'm can't toggle the last open terminal

Well that's not the place to talk about it. Sry.
