### ISSUE TITLE
It doesn't work when I set shell=pwsh

### ISSUE THREAD

**Issue by frg2089** [NvChad/nvterm#7]
When I set shell = pwsh, it doesn't work properly.

I followed neovim/neovim#13893 and it still doesn't work.

**Comment by zbirenbaum** [comment]
I don't willingly use windows so I'm not sure how to fix this. My desktop has it as a rarely touched dual boot but I don't even have neovim set up on there outside of in wsl where powershell  isn't available.

My guess based on the very little information here, is that shellcmdflag might be a buffer or window option, and not globally applied, leading to the fix not working, but it's very possibly something else.

maybe the info in `:h powershell` can help?

**Comment by siduck** [comment]
@zbirenbaum its a windows issue probably

**Comment by siduck** [comment]
closing this as its opened here https://github.com/NvChad/NvChad/issues/1063#issuecomment-1124207455

**Comment by ritchielrez** [comment]
> closing this as its opened here and that solution might work, didnt test it cuz I dont use windows https://github.com/NvChad/NvChad/issues/1063#issuecomment-1124207455

The link doesn't even exists, why? And how solve this problem?

**Comment by siduck** [comment]
oops idk the correct link, its lost somewhere

**Comment by yqwu905** [comment]
Maybe try this?:
https://github.com/akinsho/toggleterm.nvim/wiki/Tips-and-Tricks#using-toggleterm-with-powershell
It works fine for me.
