### ISSUE TITLE
Allow defining mappings outside setup

### ISSUE THREAD

**Issue by siduck** [NvChad/nvterm#8]
@zbirenbaum I defined nvtemr mappings so whichkey could register them 

![image](https://user-images.githubusercontent.com/59060246/167976523-2286dbc4-fdc5-4ef8-8c9d-65fee4d34e14.png)

but they dont work :/

**Comment by zbirenbaum** [comment]
Yeah, bc you have to do `require('nvterm.terminal')`

**Comment by siduck** [comment]
oh oops!

**Comment by siduck** [comment]
Another error 
![image](https://user-images.githubusercontent.com/59060246/167980588-8d2b1231-16a8-4bf9-8d35-228efa334477.png)

**Comment by siduck** [comment]
@zbirenbaum can you remove the old term related dead code from extensions repo?

**Comment by zbirenbaum** [comment]
> @zbirenbaum can you remove the old term related dead code from extensions repo?

Oh I thought I saw you remove that the other day. Yeah i'll take care of it.
