### ISSUE TITLE
README example mappings incorrect

### ISSUE THREAD

**Issue by zbirenbaum** [NvChad/nvterm#9]
Currently the mappings in the readme will not toggle a terminal from terminal mode.

@siduck I could fix this, but I'm a little annoyed you pushed a ton of breaking changes to the plugin without even mentioning it to the person who wrote 99.9% of the repo when there was no apparent reason other than code cleaning, so I'll let you do it. Especially since it took 20 minutes of my time to track down the issue, as I was certain I hadn't pushed any changes and thus didn't suspect it, and then another 5 to change my config to be compatible and post this.

That time would have been much better spent on the very difficult code I have due quite soon. Code which has to be compiled, making the integrated terminal quite an important part of my workflow.

You will have to change the readme to be something like this:
```
local toggle_modes = {'n', 't'}
local mappings = {
  { 'n', '<C-l>', function () require("nvterm.terminal").send(ft_cmds[vim.bo.filetype]) end },
  { toggle_modes, '<A-h>', function () require("nvterm.terminal").toggle('horizontal') end },
  { toggle_modes, '<A-v>', function () require("nvterm.terminal").toggle('vertical') end },
  { toggle_modes, '<A-i>', function () require("nvterm.terminal").toggle('float') end },
}
```

**Comment by siduck** [comment]
@zbirenbaum you were inactive these days so I preferred not to bother you, also we  ( at nvchad repo ) were facing issues with mappings i.e disabling default mappings of nvterm so I made the change quickly

**Comment by zbirenbaum** [comment]
@siduck My bad then, I didn't realize there was an actual problem it was causing, didn't notice the linked commit.

Sorry for getting mad, and thank you for being considerate of the fact that I've been really busy and haven't been on as much. I'm graduating this semester and have had finals and papers non-stop the last couple weeks. I still have a ton of papers and code due tonight and sunday, and won't finish school if they don't get done so I'm under a lot of stress :(

**Comment by siduck** [comment]
> @siduck My bad, I didn't realize there was an actual problem it was causing, didn't notice the linked commit.
> 
> Sorry for getting mad, and thank you for being considerate of the fact that I've been really busy and haven't been on as much. I'm graduating this semester and have had finals and papers non-stop the last couple weeks. I still have a ton of papers and code due tonight and sunday, and won't finish school if they don't get done so I'm under a lot of stress :(

no worries, take your time and contribute whenever you can. We have new contributors, even if we dont then i'll do it myself
